[package]
name = "lop"
version = "0.1.0"
authors = ["Scott LeBaron"]
description = "A cut(1) clone"
edition = "2018"

[dependencies]
clap = "2.33.3"

[dev-dependencies]
assert_cmd = "1.0.3"
assert_fs = "1.0.1"
predicates = "1.0.7"
